### ISSUE TITLE
BUG: Paymentmethod in order are not set correctly

### ISSUE THREAD

**Issue by losolio** [losol/eventuras#258]
Needs to clean up the orders table as paymentmethod are now stored in two different columns, and invoicing does not work for new orders.

**Comment by losviko** [comment]
temp solution: RUN sql:
`UPDATE Orders
SET PaymentMethod = PaymentMethodId
WHERE PaymentMethod IS NULL`

**Comment by gldraphael** [comment]
Seems related: https://github.com/losol/EventManagement/pull/210#issue-187513488
