### ISSUE TITLE
Add IdentityServer for identity management

### ISSUE THREAD

**Issue by losolio** [losol/eventuras#361]
Add latest stable IdentityServer4 to the solution. The task includes  
* implement identity for current application (Authorization Code Flow with PKCE)

Should facilitate later development on
* Eventuras as an OpenID Connect Identity Provider (IdP) for [TalentLMS](https://help.talentlms.com/hc/en-us/articles/360014659393-How-to-configure-SSO-with-OpenID-Connect)
* Securing APIs with OAuth2 against end-users, and the front end React participants user interface
* Securing APIs with OAuth2  against adminstrators, using a separate React front end

We will probably develop a native mobile app in 2020, and Authorization Code Flow+PKCE Grant Type may be needed later for this also.

**Comment by losolio** [comment]
Seems to be pretty easy using pkce for asp.net core part of application as well? https://www.scottbrady91.com/OpenID-Connect/ASPNET-Core-using-Proof-Key-for-Code-Exchange-PKCE

**Comment by andy-a-o** [comment]
https://github.com/losol/eventuras/pull/363
