### ISSUE TITLE
Admin UI: Image/media management

### ISSUE THREAD

**Issue by losolio** [losol/eventuras#6]
Support user uploading of images as well as inserting images as featured event image, and images in description

**Comment by losviko** [comment]
Some thoughts

![images admin ui](https://user-images.githubusercontent.com/17168367/36893828-c3f41152-1e09-11e8-9c68-45aa2163834a.png)

**Comment by gldraphael** [comment]
Could we rename this to "Support uploading images for Events"?

**Comment by losolio** [comment]
Closing this. Think it is better to look at headless or even headed cms.
