### ISSUE TITLE
Product Registration Issue

### ISSUE THREAD

**Issue by meinte** [losol/eventuras#616]
### **Describe the bug**
When trying to register a product after registering for an event, it returns a 403.

### **To Reproduce**
Create a new event
`POST {{baseUrl}}/v3/events`

`
{
    "title": "This is a temp Event - 14",
    "slug": "tempevent14",
    "type": "Course",
    "status": "RegistrationsOpen",
    "organizationId": 1,
    "category": "thisisacategory",
    "description": "Feel free to remove",
    "manageRegistrations": true,
    "onDemand": true,
    "featured": true,
    "program": "Ths is a program",
    "practicalInformation": "Some practical info",
    "location": "The Netherlands",
    "city": "Amsterdam",
    "startDate":"2023-10-10",
    "endDate":"2023-11-11",
    "published":"true"
}
`

After this, register for that event as a user:
`POST {{baseUrl}}/v3/registrations`

`
{
    "userId": "{{userId}}",
    "eventId": 19,
    "customer": {
        "vatNumber": "321321",
        "name": "Meinte van't Kruis",
        "email": "meinte@gmail.com",
        "zip": "321321",
        "city": "Amsterdam",
        "country": "The Netherlands",
        "invoiceReference": "reference1234"
    },
    "notes": "NOT IMPLEMENTED",
    "type": "Participant",
    "createOrder": true,
    "paymentMethod": "PowerOfficeEmailInvoice"
}
`

Finally update products

`PUT {{baseUrl}}/v3/registrations/70/products`

`{
    "lines":{
        {
            "productId":12,
            "quantity":"1"
        }
    }
}`

The final call returns a `403 forbidden`

### **Expected behavior**
It should accept the call and either respond with success (and return the created object), or a 400 if the request is invalid

**Error message** 
```
403 forbidden
```

**Comment by losolio** [comment]
I am not sure which business logic there is for now. In the future the organizaer should probably choose between some policies: 

1. Restrictive - Cancellations and modifications are only allowed within 24 hours after registration
2. Flexible - Cancellations and modifications are allowed until last cancellation date (`LastCancellationDate` in domain model). 
3. Possibly some more policies... Like add, but not remove and so on.. 

**For now i think we could just start with the restrictive policy:** 

1. Participants are allowed to edit products and modify their order within 24 hours after initial registration. 
1. Organization admin for the organization owning the event are allowed to cancel registration add orders at any time
1. System admin has the same rights as organization admins, but for any organization. 

Note that to nobody are allowed to edit invoiced orders, so if orders are invoiced and admin request a product change, the orderautomagic function should be used!

**Comment by yura-b** [comment]
@meinte 

Can you provide me more information about `{ "lines":{ { "productId":12, "quantity":"1" } } }` product?
Does it exist in the event (or in collection), does it have any variants, minimal quantity or other settings?

Also, I did not found the route `PUT {{baseUrl}}/v3/registrations/70/products`, there is only `POST {{baseUrl}}/v3/registrations/70/products`.
